# Generated by Django 5.2.7 on 2025-10-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('useremail', models.EmailField(max_length=254)),
                ('usermobile', models.IntegerField()),
                ('userpassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customerlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usermobile', models.IntegerField()),
                ('userpassword', models.CharField(max_length=50)),
            ],
        ),
    ]
