# Generated by Django 5.2.7 on 2025-10-10 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_userlogin_userprofile_delete_customerdetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='mobile',
        ),
    ]
