# Generated by Django 5.2.7 on 2025-10-10 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_remove_userlogin_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='email',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='username',
        ),
    ]
