# Generated by Django 5.2.7 on 2025-10-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0004_rename_email_userlogin_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='name',
        ),
    ]
