# Generated by Django 5.2.7 on 2025-10-24 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0006_order_product_salesperson_delete_userlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grocery.salesperson'),
        ),
    ]
