# Generated by Django 5.2.7 on 2025-10-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0010_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperson',
            name='total_deliveries',
        ),
        migrations.AddField(
            model_name='salesperson',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
